version: '2.4'
services:
  app:
    image: 'anatoliysharov/cardatamanager:0.0.1-SNAPSHOT'
          
    build:
      context: .
    
    container_name: car-rest-service
    
    depends_on:
      - db

    ports:
      - "8080:8081"
    
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
          
  db:
    image: 'postgres:14-alpine' #please check alpine version in docker hub
    
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=cardata
