TRUNCATE TABLE car CASCADE;
TRUNCATE TABLE model_category CASCADE;
TRUNCATE TABLE model_year CASCADE;
TRUNCATE TABLE year CASCADE;
TRUNCATE TABLE category CASCADE;
TRUNCATE TABLE model CASCADE;
TRUNCATE TABLE manufacturer CASCADE;
