CREATE TABLE manufacturer(
id BIGSERIAL PRIMARY KEY,
name CHARACTER VARYING(100) UNIQUE
);

CREATE TABLE category(
id BIGSERIAL PRIMARY KEY,
name CHARACTER VARYING(100) UNIQUE
);

CREATE TABLE year(
id BIGSERIAL PRIMARY KEY,
year INTEGER NOT NULL UNIQUE
);

CREATE TABLE model(
id BIGSERIAL PRIMARY KEY,
name CHARACTER VARYING(100) NOT NULL,
manufacturer_id BIGINT REFERENCES manufacturer(id) ON DELETE CASCADE NOT NULL,
UNIQUE(name, manufacturer_id)
);

CREATE TABLE model_year(
model_id BIGINT NOT NULL,
year_id BIGINT NOT NULL,
UNIQUE(model_id, year_id) 
);

CREATE TABLE model_category(
model_id BIGINT NOT NULL,
category_id BIGINT NOT NULL,
UNIQUE(model_id,category_id)
);

CREATE TABLE car(
id BIGSERIAL PRIMARY KEY,
object_id CHARACTER VARYING(10) NOT NULL UNIQUE,
manufacturer_id BIGINT REFERENCES manufacturer(id) ON DELETE CASCADE NOT NULL,
year_id BIGINT REFERENCES year(id) ON DELETE CASCADE NOT NULL,
model_id BIGINT REFERENCES model(id) ON DELETE CASCADE NOT NULL,
category_id BIGINT REFERENCES category(id) ON DELETE CASCADE NOT NULL
);